/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sendjson_CONSTANTS_H
#define sendjson_CONSTANTS_H

#include "sendjson_types.h"

namespace sendjson {

class sendjsonConstants {
 public:
  sendjsonConstants();

};

extern const sendjsonConstants g_sendjson_constants;

} // namespace

#endif
