/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mbloghash_constants.h"

namespace mbloghash {

const mbloghashConstants g_mbloghash_constants;

mbloghashConstants::mbloghashConstants() {
}

} // namespace

