/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mbloghash_CONSTANTS_H
#define mbloghash_CONSTANTS_H

#include "mbloghash_types.h"

namespace mbloghash {

class mbloghashConstants {
 public:
  mbloghashConstants();

};

extern const mbloghashConstants g_mbloghash_constants;

} // namespace

#endif
